apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
spec:
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: nexus-registry.eastus.cloudapp.azure.com:8088/fleetman-queue:d541bbd
