apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nexus-registry.eastus.cloudapp.azure.com:8086/fleetman-webapp:a6b9057-dev
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice