apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    matchLabels:
      app: fleetman-api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
      - name: fleetman-api-gateway
        image: nexus-registry.eastus.cloudapp.azure.com:8086/fleetman-api-gateway:f07e1b5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice