---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
    - name: rest-interface
      port: 8080
      targetPort: 8080
      nodePort: 30021
  type: NodePort