apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
spec:
  selector:
    matchLabels:
      app: fleetman-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
      - name: fleetman-webapp
        image: nexus-registry.eastus.cloudapp.azure.com:8086/fleetman-webapp:57607ad
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: local-microservice