apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
spec:
  selector:
    matchLabels:
      app: fleetman-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
      - name: fleetman-webapp
        image: nexus-registry.eastus.cloudapp.azure.com:8085/fleetman-webapp.:latest12
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: local-microservice
      imagePullSecrets:
      - name: regcred    