apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: nexus-registry.eastus.cloudapp.azure.com:8086/fleetman-api-gateway:662a994-dev
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice